language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  # Build udagram-api-feed
  - docker build -t api-feed-1 ./udagram-api-feed
  - docker tag api-feed-1 datpd7/api-feed-1:v1
  # Build udagram-api-user
  - docker build -t api-user-1 ./udagram-api-user
  - docker tag api-user-1 datpd7/api-user-1:v1
  # Build udagram-frontend
  - docker build -t uda-fe ./udagram-frontend
  - docker tag uda-fe datpd7/uda-fe:v1
  # Build reverseproxy
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy datpd7/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push datpd7/api-feed-1:v1
  - docker push datpd7/api-user-1:v1
  - docker push datpd7/uda-fe:v1
  - docker push datpd7/reverseproxy:v1