apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-feed-1
  labels:
    app: api-feed-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-feed-1
  template:
    metadata:
      labels:
        app: api-feed-1
    spec:
      containers:
      - name: api-feed-1
        image: datpd7/api-feed-1:v1
        resources:
          requests:
            memory: "1024Mi"        # Minimum memory request
            cpu: "500m"            # Minimum CPU request
          limits:
            memory: "2048Mi"        # Maximum memory limit
            cpu: "1"
        volumeMounts:
        - name: aws-credentials-volume
          mountPath: /root/.aws/credentials
          subPath: credentials
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: POSTGRES_DB
        - name: AWS_BUCKET_ACCESS_POINT
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AWS_BUCKET_ACCESS_POINT
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AWS_PROFILE
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: JWT_SECRET
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: URL
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/v0/feed
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 60
      volumes:
      - name: aws-credentials-volume
        secret:
          secretName: aws-credentials